version: '3.8'
services:
  stylegan2:
    privileged: true
    tty: true
    build: .
    image: mystylegan2:latest
    container_name: 'MyStyleGan2'
    runtime: nvidia
    environment: 
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /home/$USER/share:/share